<?php
# This file is part of InvisCMS .
#
#    InvisCMS is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Foobar is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with InvisCMS.  If not, see <http://www.gnu.org/licenses/>.
?><div class="dT" style='width:100%;margin-left:0%;'>
	  <span class="header">Выберите интересующий вас раздел модуля:</span>
	  <ul>
	      <li>
				 <button onclick='javascript:core.loadPage("banners","clients");return false;'>
							Клиенты
			    </button>
			</li>
	      <li>
				 <button onclick='javascript:core.loadPage("banners","accounts");return false;'>
				 			Баннеры
				 </button>
		   </li>
	      <li>
				 <button onclick='javascript:core.loadPage("banners","settings");return false;'>
				 			Настройки
				 </button>
		   </li>
	  </ul>
</div>
